apiVersion: v1
kind: Pod
metadata:
  name: test-pod1
spec: 
  schedulerName: my-custom-scheduler
  containers:
  - name: pause
    image: k8s.gcr.io/pause:3.1

---

apiVersion: v1
kind: Pod
metadata:
  name: test-pod2
spec:
  schedulerName: my-custom-scheduler
  containers:
  - name: pause
    image: k8s.gcr.io/pause:3.1

---

apiVersion: v1
kind: Pod
metadata:
  name: test-pod3
spec:
  schedulerName: my-custom-scheduler
  containers:
  - name: pause
    image: k8s.gcr.io/pause:3.1
